NKSLK/Controllers/StatisticsController.cs
using NKSLK.DAO;
using PagedList;
using System;
using System.Web.Mvc;

namespace NKSLK.Controllers
{
    [Authorize]
    public class StatisticsController : Controller
    {
        StatisticsDAO dao = new StatisticsDAO();

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult MostPrevalentWorkStatistics
            (int page = 1,
             int pageSize = 10,
             string criterion = "All",
             string selectedDate = null,
             string order = null)
        {
            if (ModelState.IsValid)
            {
                if (selectedDate == null)
                {
                    if (criterion == "Week")
                    {
                        selectedDate = DateTime.Today.ToString("dd/MM/yyyy");
                    }
                    else
                    {
                        selectedDate = DateTime.Today.ToString("MM/yyyy");
                    }
                }
                var model = dao.GetMostPrevalentWorks(criterion, selectedDate, order);
                model = model.ToPagedList(page, pageSize);

                ViewBag.page = page;
                ViewBag.pageSize = pageSize;
                ViewBag.criterion = criterion;
                ViewBag.selectedDate = selectedDate;
                ViewBag.ID_Order = order == "ID_asc" ? "ID_desc" : "ID_asc";
                ViewBag.Name_Order = order == "Name_asc" ? "Name_desc" : "Name_asc";
                ViewBag.Quantity_Order = String.IsNullOrEmpty(order) ? "Quantity_asc" : "";
                ViewBag.order = order;

                return View(model);
            }
            else
            {
                ModelState.AddModelError("", "Error");
            }

            return View();
        }

        public ActionResult ThirdShiftStatistics
           (int page = 1,
            int pageSize = 10,
            string criterion = "All",
            string selectedDate = null,
            string order = null)
        {
            if (ModelState.IsValid)
            {
                if (selectedDate == null)
                {
                    if (criterion == "Week")
                    {
                        selectedDate = DateTime.Today.ToString("dd/MM/yyyy");
                    }
                    else
                    {
                        selectedDate = DateTime.Today.ToString("MM/yyyy");
                    }
                }
                var model = dao.GetThirdShifts(criterion, selectedDate, order);
                model = model.ToPagedList(page, pageSize);

                ViewBag.page = page;
                ViewBag.pageSize = pageSize;
                ViewBag.criterion = criterion;
                ViewBag.selectedDate = selectedDate;
                ViewBag.ID_Order = String.IsNullOrEmpty(order) ? "ID_desc" : "";
                ViewBag.Name_Order = order == "Name_asc" ? "Name_desc" : "Name_asc";
                ViewBag.order = order;

                return View(model);
            }
            else
            {
                ModelState.AddModelError("", "Error");
            }

            return View();
        }

        public ActionResult NKSLKStatistics
            (int page = 1,
             int pageSize = 10,
             string criterion = "All",
             string selectedDate = null,
             string search = null,
             int idLabour = 0,
             string order = null)
        {
            if (ModelState.IsValid)
            {               
                if (selectedDate == null)
                {
                    if (criterion == "Week")
                    {
                        selectedDate = DateTime.Today.ToString("dd/MM/yyyy");
                    }
                    else
                    {
                        selectedDate = DateTime.Today.ToString("MM/yyyy");
                    }
                }
                var model = dao.GetNKSLKs(criterion, selectedDate, search, idLabour, order);
                model = model.ToPagedList(page, pageSize);

                ViewBag.page = page;
                ViewBag.pageSize = pageSize;
                ViewBag.criterion = criterion;
                ViewBag.search = search;
                ViewBag.selectedDate = selectedDate;
                ViewBag.labourList = new SelectList(dao.GetLabourList(), "ID_CONGNHAN", "HoTen");
                ViewBag.idLabour = idLabour;
                ViewBag.ID_Order = order == "ID_asc" ? "ID_desc" : "ID_asc";
                ViewBag.LabourName_Order = order == "LabourName_asc" ? "LabourName_desc" : "LabourName_asc";
                ViewBag.Day_Order = String.IsNullOrEmpty(order) ? "Day_desc" : "";
                ViewBag.Start_Order = order == "Start_asc" ? "Start_desc" : "Start_asc";
                ViewBag.End_Order = order == "End_asc" ? "End_desc" : "End_asc";
                ViewBag.WorkName_Order = order == "WorkName_asc" ? "WorkName_desc" : "WorkName_asc";
                ViewBag.ProductName_Order = order == "ProductName_asc" ? "ProductName_desc" : "ProductName_asc";
                ViewBag.Quantity_Order = order == "Quantity_asc" ? "Quantity_desc" : "Quantity_asc";
                ViewBag.Batch_Order = order == "Batch_asc" ? "Batch_desc" : "Batch_asc";
                ViewBag.order = order;

                return View(model);
            }
            else
            {
                ModelState.AddModelError("", "Error");
            }

            return View();
        }

        public ActionResult SalaryStatistics
            (int page = 1,
             int pageSize = 10,
             string criterion = "Week",
             string selectedDate = null,
             string order = null)
        {
            if (ModelState.IsValid)
            {
                if (selectedDate == null)
                {
                    if (criterion == "Week")
                    {
                        selectedDate = DateTime.Today.ToString("dd/MM/yyyy");
                    }
                    else
                    {
                        selectedDate = DateTime.Today.ToString("MM/yyyy");
                    }
                }
                var model = dao.GetSalaries(criterion, selectedDate, order);
                model = model.ToPagedList(page, pageSize);

                ViewBag.page = page;
                ViewBag.pageSize = pageSize;
                ViewBag.criterion = criterion;
                ViewBag.selectedDate = selectedDate;
                ViewBag.ID_Order = String.IsNullOrEmpty(order) ? "ID_desc" : "";
                ViewBag.Name_Order = order == "Name_asc" ? "Name_desc" : "Name_asc";
                ViewBag.Salary_Order = order == "Salary_asc" ? "Salary_desc" : "Salary_asc";
                ViewBag.order = order;

                return View(model);
            }
            else
            {
                ModelState.AddModelError("", "Error");
            }

            return View();
        }

        public ActionResult WorkdayStatistics
            (int page = 1,
             int pageSize = 10,
             string selectedDate = null,
             int idLabour = 0,
             string order = null)
        {

            if (ModelState.IsValid)
            {
                if (selectedDate == null)
                {
                    selectedDate = DateTime.Today.ToString("MM/yyyy");
                }
                var model = dao.GetWorkdays(selectedDate, idLabour, order);
                model = model.ToPagedList(page, pageSize);

                ViewBag.page = page;
                ViewBag.pageSize = pageSize;
                ViewBag.selectedDate = selectedDate;
                ViewBag.labourList = new SelectList(dao.GetLabourList(), "ID_CONGNHAN", "HoTen");
                ViewBag.idLabour = idLabour;
                ViewBag.ID_Order = String.IsNullOrEmpty(order) ? "ID_desc" : "";
                ViewBag.Name_Order = order == "Name_asc" ? "Name_desc" : "Name_asc";
                ViewBag.Workday_Order = order == "Workday_asc" ? "Workday_desc" : "Workday_asc";
                ViewBag.order = order;

                return View(model);
            }
            else
            {
                ModelState.AddModelError("", "Error");
            }

            return View();
        }

        public ActionResult WorkinghourStatistics
            (int page = 1,
             int pageSize = 10,
             string selectedDate = null,
             string order = null)
        {
            if (ModelState.IsValid)
            {
                if (selectedDate == null)
                {
                    selectedDate = DateTime.Today.ToString("dd/MM/yyyy");
                }
                var model = dao.GetWorkinghours(selectedDate, order);
                model = model.ToPagedList(page, pageSize);

                ViewBag.page = page;
                ViewBag.pageSize = pageSize;
                ViewBag.selectedDate = selectedDate;
                ViewBag.ID_Order = String.IsNullOrEmpty(order) ? "ID_desc" : "";
                ViewBag.Name_Order = order == "Name_asc" ? "Name_desc" : "Name_asc";
                ViewBag.Workinghour_Order = order == "Workinghour_asc" ? "Workinghour_desc" : "Workinghour_asc";
                ViewBag.order = order;

                return View(model);
            }
            else
            {
                ModelState.AddModelError("", "Error");
            }
            return View();
        }
    }
}

NKSLK/Views/Statistics/Index.cshtml
@{
    ViewBag.Title = "Thống kê";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Thống kê</title>
    <link href="~/Content/admin/css/admin.css" rel="stylesheet">
    <link href="~/Content/admin/css/styles.css" rel="stylesheet" />
    <link href="~/Content/css/style.css" rel="stylesheet">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/js/all.min.js" crossorigin="anonymous"></script>
</head>

<body>
    <h2>Thống kê</h2>
    <div class="row p-t-20">
        <div class="col-lg-6 col-md-12">
            <div class="card text-white mb-4" style="background-color: #b71c1c">
                <div class="card-body text-white">Thống kê công việc có nhiều NKSLK nhất</div>
                <div class="card-footer d-flex align-items-center justify-content-between">
                    <a class="small text-white stretched-link" href="~/Statistics/MostPrevalentWorkStatistics">Chi tiết</a>
                    <div class="small text-white"><i class="fas fa-angle-right"></i></div>
                </div>
            </div>
        </div>
        <div class="col-lg-6 col-md-12">
            <div class="card text-white mb-4" style="background-color: #f4511e">
                <div class="card-body text-white">Thống kê công nhân làm việc ca 3 (22h - 6h)</div>
                <div class="card-footer d-flex align-items-center justify-content-between">
                    <a class="small text-white stretched-link" href="~/Statistics/ThirdShiftStatistics">Chi tiết</a>
                    <div class="small text-white"><i class="fas fa-angle-right"></i></div>
                </div>
            </div>
        </div>
        <div class="col-lg-6 col-md-12">
            <div class="card text-white mb-4" style="background-color: #2e7d32">
                <div class="card-body text-white">Thống kê NKSLK của nhân viên theo tuần, tháng</div>
                <div class="card-footer d-flex align-items-center justify-content-between">
                    <a class="small text-white stretched-link" href="~/Statistics/NKSLKStatistics">Chi tiết</a>
                    <div class="small text-white"><i class="fas fa-angle-right"></i></div>
                </div>
            </div>
        </div>
        <div class="col-lg-6 col-md-12">
            <div class="card text-white mb-4" style="background-color: #0277bd">
                <div class="card-body text-white">Thống kê bảng lương sản phẩm của công nhân</div>
                <div class="card-footer d-flex align-items-center justify-content-between">
                    <a class="small text-white stretched-link" href="~/Statistics/SalaryStatistics">Chi tiết</a>
                    <div class="small text-white"><i class="fas fa-angle-right"></i></div>
                </div>
            </div>
        </div>
        <div class="col-lg-6 col-md-12">
            <div class="card text-white mb-4" style="background-color: #512da8">
                <div class="card-body text-white">Thống kê số ngày công đi làm trong tháng của công nhân</div>
                <div class="card-footer d-flex align-items-center justify-content-between">
                    <a class="small text-white stretched-link" href="~/Statistics/WorkdayStatistics">Chi tiết</a>
                    <div class="small text-white"><i class="fas fa-angle-right"></i></div>
                </div>
            </div>
        </div>
        <div class="col-lg-6 col-md-12">
            <div class="card text-white mb-4" style="background-color: #00796b">
                <div class="card-body text-white">Thống kê danh mục công nhân có số giờ công trong tuần vượt chuẩn</div>
                <div class="card-footer d-flex align-items-center justify-content-between">
                    <a class="small text-white stretched-link" href="~/Statistics/WorkinghourStatistics">Chi tiết</a>
                    <div class="small text-white"><i class="fas fa-angle-right"></i></div>
                </div>
            </div>
        </div>
    </div>
</body>
</html>

NKSLK/Views/Statistics/MostPrevalentWorkStatistics.cshtml
@model IEnumerable<NKSLK.EF.MostPrevalentWorkModel>
@using PagedList.Mvc;
@using PagedList;
@{
    ViewBag.Title = "Thống kê";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <title>Thống kê</title>
    <link href="~/Content/admin/css/admin.css" rel="stylesheet">
    <link href="~/Content/admin/css/styles.css" rel="stylesheet">
    <link href="~/Content/css/style.css" rel="stylesheet">
    <link href="~/Content/themes/base/jquery-ui.min.css" rel="stylesheet" />
    <script src="~/Scripts/jquery-3.6.0.min.js"></script>
    <script src="~/Scripts/jquery-ui-1.13.0.min.js"></script>
    <script src="~/Scripts/moment.js"></script>
    <script src="~/Scripts/Custom/custom.js"></script>
</head>
<body>
    <div class="row">
        <div class="col-lg-12">
            <h3 style="display:inline ; float:right">Thống kê công việc có nhiều NKSLK nhất</h3>
        </div>
    </div>
    @using (Html.BeginForm("MostPrevalentWorkStatistics", "Statistics", FormMethod.Get))
    {
        <div class="row p-t-8">
            <div class="col-lg-6">
                <div class="float-left">
                    @*criterion*@
                    <h5 style="display:inline" class="m-r-3">Tiêu chí</h5>
                    @Html.DropDownList("criterion",
                     new SelectList(new List<SelectListItem>
                         {
                            new SelectListItem { Selected = true, Text = "Tất cả", Value = "All"},
                            new SelectListItem { Selected = true, Text = "Tuần", Value = "Week"},
                            new SelectListItem { Selected = true, Text = "Tháng", Value = "Month"},
                         }, "Value", "Text"),
                     new { @class = "dataTable-selector", @id = "criterion" })

                    @*selecteDate*@
                    @Html.TextBox("selectedDate", "", new
                    {
                        @class = "dataTable-input date-picker",
                        @style = "width: 175px; display:inline",
                        @Value = ViewBag.selectedDate,
                        @readonly = true,
                        @id = "selectedDate"
                    })
                </div>
            </div>
            <div class="col-lg-4">
                <div class="float-left">
                    @*pageSize*@
                    <h5 style="display:inline" class="m-r-3">Số bản ghi</h5>
                    @Html.DropDownList("pageSize",
                     new SelectList(new List<SelectListItem>
                         {
                            new SelectListItem { Selected = true, Text = "5", Value = "5"},
                            new SelectListItem { Selected = true, Text = "10", Value = "10"},
                            new SelectListItem { Selected = true, Text = "15", Value = "15"},
                            new SelectListItem { Selected = true, Text = "20", Value = "20"},
                            new SelectListItem { Selected = true, Text = "25", Value = "25"}
                         }, "Value", "Text"),
                     new { @class = "dataTable-selector" })
                </div>
            </div>
            <div class="col-lg-2">
                <div class="float-right">
                    <button class="btn btn-primary m-b-3" style="padding: 0.35rem 0.75rem; line-height:1.2">Thống kê</button>
                </div>
            </div>
        </div>
    }
    <div class="row p-t-15">
        <div class=" col-lg-12">
            <table class="table">
                <tr>
                    <th style="background-color: #593bdb !important; color: #fff !important; width: 10%; text-align: center">
                        STT
                    </th>
                    @{ string symbol; }
                    <th style="background-color: #593bdb !important; color: #fff !important; width: 20%; text-align: center">
                        @{symbol = ViewBag.order == "ID_asc" ? " ⯅" : ViewBag.order == "ID_desc" ? " ⯆" : "";}
                        @Html.ActionLink(WebUtility.HtmlDecode(Html.DisplayNameFor(model => model.ID_CONGVIEC).ToHtmlString() + symbol),
                                        "MostPrevalentWorkStatistics",
                                        new
                                        {
                                            page = 1,
                                            pageSize = ViewBag.pageSize,
                                            criterion = ViewBag.criterion,
                                            selectedDate = ViewBag.selectedDate,
                                            order = ViewBag.ID_Order
                                        }, new { @style = "color: #fff" })
                    </th>
                    <th style="background-color: #593bdb !important; color: #fff !important; width: 35%; text-align: center">
                        @{symbol = ViewBag.order == "Name_asc" ? " ⯅" : ViewBag.order == "Name_desc" ? " ⯆" : "";}
                        @Html.ActionLink(WebUtility.HtmlDecode(Html.DisplayNameFor(model => model.TenCongViec).ToHtmlString() + symbol),
                                        "MostPrevalentWorkStatistics",
                                        new
                                        {
                                            page = 1,
                                            pageSize = ViewBag.pageSize,
                                            criterion = ViewBag.criterion,
                                            selectedDate = ViewBag.selectedDate,
                                            order = ViewBag.Name_Order
                                        }, new { @style = "color: #fff" })
                    </th>
                    <th style="background-color: #593bdb !important; color: #fff !important; width: 35%; text-align: center">
                        @{symbol = ViewBag.order == null ? " ⯆" : ViewBag.order == "Quantity_asc" ? " ⯅" : "";}
                        @Html.ActionLink(WebUtility.HtmlDecode(Html.DisplayNameFor(model => model.SoLuong).ToHtmlString() + symbol),
                                        "MostPrevalentWorkStatistics",
                                        new
                                        {
                                            page = 1,
                                            pageSize = ViewBag.pageSize,
                                            criterion = ViewBag.criterion,
                                            selectedDate = ViewBag.selectedDate,
                                            order = ViewBag.Quantity_Order
                                        }, new { @style = "color: #fff" })
                    </th>
                </tr>
                @if (Model != null)
                {
                    int i = (ViewBag.page - 1) * ViewBag.pageSize + 1;
                    foreach (var item in Model)
                    {
                        <tr>
                            <td style="color: #000 !important; text-align: center">
                                @Convert.ToInt32(i)
                            </td>
                            <td style="color: #000 !important; text-align: center">
                                @Html.DisplayFor(modelItem => item.ID_CONGVIEC)
                            </td>
                            <td style="color: #000 !important; text-align: center">
                                @Html.DisplayFor(modelItem => item.TenCongViec)
                            </td>
                            <td style="color: #000 !important; text-align: center">
                                @Html.DisplayFor(modelItem => item.SoLuong)
                            </td>
                        </tr>
                        i++;
                    }
                }
            </table>
        </div>
    </div>
    <div class="row p-t-10">
        <div class="col-lg-12">
            <div class="dataTable-pagination" style="float:right">
                @Html.PagedListPager((IPagedList)Model,
                page => Url.Action("MostPrevalentWorkStatistics",
                new
                {
                    page,
                    pageSize = ViewBag.pageSize,
                    criterion = ViewBag.criterion,
                    selectedDate = ViewBag.selectedDate,
                    order = ViewBag.order
                }),
                new PagedListRenderOptions
                {
                    MaximumPageNumbersToDisplay = 5,
                    LinkToPreviousPageFormat = "<<",
                    LinkToNextPageFormat = ">>",
                    LinkToFirstPageFormat = "First",
                    LinkToLastPageFormat = "Last"
                });
            </div>
        </div>
    </div>
</body>
</html>

NKSLK/Views/Statistics/SalaryStatistics.cshtml
@model IEnumerable<NKSLK.EF.SalaryModel>
@using PagedList.Mvc;
@using PagedList;
@{
    ViewBag.Title = "Thống kê";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <title>Thống kê</title>
    <link href="~/Content/admin/css/admin.css" rel="stylesheet">
    <link href="~/Content/admin/css/styles.css" rel="stylesheet">
    <link href="~/Content/css/style.css" rel="stylesheet">
    <link href="~/Content/themes/base/jquery-ui.min.css" rel="stylesheet" />
    <script src="~/Scripts/jquery-3.6.0.min.js"></script>
    <script src="~/Scripts/jquery-ui-1.13.0.min.js"></script>
    <script src="~/Scripts/moment.js"></script>
    <script src="~/Scripts/Custom/custom.js"></script>
</head>
<body>
    <div class="row">
        <div class="col-lg-12">
            <h3 style="display:inline ; float:right">Thống kê bảng lương sản phẩm của công nhân</h3>
        </div>
    </div>
    @using (Html.BeginForm("SalaryStatistics", "Statistics", FormMethod.Get))
    {
        <div class="row p-t-8">
            <div class="col-lg-6">
                <div class="float-left">
                    @*criterion*@
                    <h5 style="display:inline" class="m-r-3">Tiêu chí</h5>
                    @Html.DropDownList("criterion",
                     new SelectList(new List<SelectListItem>
                         {
                            new SelectListItem { Selected = true, Text = "Tuần", Value = "Week"},
                            new SelectListItem { Selected = true, Text = "Tháng", Value = "Month"},
                         }, "Value", "Text"),
                     new { @class = "dataTable-selector", @id = "criterion" })

                    @*selecteDate*@
                    @Html.TextBox("selectedDate", "", new
                    {
                        @class = "dataTable-input date-picker",
                        @style = "width: 175px; display:inline",
                        @Value = ViewBag.selectedDate,
                        @readonly = true,
                        @id = "selectedDate"
                    })
                </div>
            </div>
            <div class="col-lg-4">
                <div class="float-left">
                    @*pageSize*@
                    <h5 style="display:inline" class="m-r-3">Số bản ghi</h5>
                    @Html.DropDownList("pageSize",
                     new SelectList(new List<SelectListItem>
                         {
                            new SelectListItem { Selected = true, Text = "5", Value = "5"},
                            new SelectListItem { Selected = true, Text = "10", Value = "10"},
                            new SelectListItem { Selected = true, Text = "15", Value = "15"},
                            new SelectListItem { Selected = true, Text = "20", Value = "20"},
                            new SelectListItem { Selected = true, Text = "25", Value = "25"}
                         }, "Value", "Text"),
                     new { @class = "dataTable-selector" })
                </div>
            </div>
            <div class="col-lg-2">
                <div class="float-right">
                    <button class="btn btn-primary m-b-3" style="padding: 0.35rem 0.75rem; line-height:1.2">Thống kê</button>
                </div>
            </div>
        </div>
    }
    <div class="row p-t-15">
        <div class=" col-lg-12">
            <table class="table">
                <tr>
                    <th style="background-color: #593bdb !important; color: #fff !important; width: 10%; text-align: center">
                        STT
                    </th>
                    @{ string symbol; }
                    <th style="background-color: #593bdb !important; color: #fff !important; width: 20%; text-align: center">
                        @{symbol = ViewBag.order == null ? " ⯅" : ViewBag.order == "ID_desc" ? " ⯆" : "";}
                        @Html.ActionLink(WebUtility.HtmlDecode(Html.DisplayNameFor(model => model.ID_CONGNHAN).ToHtmlString() + symbol),
                                        "SalaryStatistics",
                                        new
                                        {
                                            page = 1,
                                            pageSize = ViewBag.pageSize,
                                            criterion = ViewBag.criterion,
                                            selectedDate = ViewBag.selectedDate,
                                            order = ViewBag.ID_Order
                                        }, new { @style = "color: #fff" })
                    </th>
                    <th style="background-color: #593bdb !important; color: #fff !important; width: 35%; text-align: center">
                        @{symbol = ViewBag.order == "Name_asc" ? " ⯅" : ViewBag.order == "Name_desc" ? " ⯆" : "";}
                        @Html.ActionLink(WebUtility.HtmlDecode(Html.DisplayNameFor(model => model.HoTen).ToHtmlString() + symbol),
                                        "SalaryStatistics",
                                        new
                                        {
                                            page = 1,
                                            pageSize = ViewBag.pageSize,
                                            criterion = ViewBag.criterion,
                                            selectedDate = ViewBag.selectedDate,
                                            order = ViewBag.Name_Order
                                        }, new { @style = "color: #fff" })
                    </th>
                    <th style="background-color: #593bdb !important; color: #fff !important; width: 35%; text-align: center">
                        @{symbol = ViewBag.order == "Salary_asc" ? " ⯅" : ViewBag.order == "Salary_desc" ? " ⯆" : "";}
                        @Html.ActionLink(WebUtility.HtmlDecode(Html.DisplayNameFor(model => model.LuongSanPham).ToHtmlString() + symbol),
                                        "SalaryStatistics",
                                        new
                                        {
                                            page = 1,
                                            pageSize = ViewBag.pageSize,
                                            criterion = ViewBag.criterion,
                                            selectedDate = ViewBag.selectedDate,
                                            order = ViewBag.Salary_Order
                                        }, new { @style = "color: #fff" })
                    </th>
                </tr>
                @if (Model != null)
                {
                    int i = (ViewBag.page - 1) * ViewBag.pageSize + 1;
                    foreach (var item in Model)
                    {
                        <tr>
                            <td style="color: #000 !important; text-align: center">
                                @Convert.ToInt32(i)
                            </td>
                            <td style="color: #000 !important; text-align: center">
                                @Html.DisplayFor(modelItem => item.ID_CONGNHAN)
                            </td>
                            <td style="color: #000 !important; text-align: center">
                                @Html.DisplayFor(modelItem => item.HoTen)
                            </td>
                            <td style="color: #000 !important; text-align: center">
                                @string.Format("{0:#,0}", Convert.ToInt32(item.LuongSanPham))
                            </td>
                        </tr>
                        i++;
                    }
                }
            </table>
        </div>
    </div>
    <div class="row p-t-10">
        <div class="col-lg-12">
            <div class="dataTable-pagination" style="float:right">
                @Html.PagedListPager((IPagedList)Model,
                page => Url.Action("SalaryStatistics",
                new
                {
                    page,
                    pageSize = ViewBag.pageSize,
                    criterion = ViewBag.criterion,
                    selectedDate = ViewBag.selectedDate,
                    order = ViewBag.order
                }),
                new PagedListRenderOptions
                {
                    MaximumPageNumbersToDisplay = 5,
                    LinkToPreviousPageFormat = "<<",
                    LinkToNextPageFormat = ">>",
                    LinkToFirstPageFormat = "First",
                    LinkToLastPageFormat = "Last"
                });
            </div>
        </div>
    </div>
</body>
</html>